.PHONY : Balanced_Position Counting_Sort


all: Balanced_Position.c Counting_Sort.c 
	gcc -o Balanced_Position Balanced_Position.c 
	gcc -o Counting_Sort Counting_Sort.c 

clean:
	rm -rf Balanced_Position Counting_Sort
